{% set name = "MariaDB-Context-Manager" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mariadb_context_manager-{{ version }}.tar.gz
  sha256: ad25278d04ffec5e9f7bba4b5f30baf2e9620ed6313532bf4cb6032dfbd46f41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - mariadb >=1.1.10

test:
  imports:
    - contextManager
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/MariaDB-Context-Manager
  summary: An easy to use mariadb context manager
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - avgra3
