{% set name = "MariaDB-Context-Manager" %}
{% set version = "0.1.16" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mariadb_context_manager-{{ version }}.tar.gz
  sha256: c61150620b3f4204ef544bc761e022619fbd1b9ba3d21932c1f4d11826c0cdda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - mariadb >=1.1.10

test:
  imports:
    - contextManager
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pypi.python.org/pypi/MariaDB-Context-Manager
  summary: An easy to use mariadb context manager
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - avgra3
